os:
    - linux

language: python

python:
    # - 2.6 No longer supported on Travis
    - 2.7
    # - 3.3 No longer supported on Travis
    - 3.4
    - 3.5
    - 3.6
    - 3.7
    - 3.8
    - pypy
    - pypy3.5

before_script:
    - pip install -r requirements-dev.txt

script:
    - python sh.py travis
    - python -m flake8 sh.py test.py
    - if python -c 'import sys; sys.exit(int(not sys.version_info >= (3, 5)))' ; then python setup.py check --restructuredtext --metadata --strict ; fi

after_success:
    - coveralls
